### ISSUE TITLE
Result showing 0

### ISSUE THREAD

**Issue by vishu002** [Jayanthbm/triviabot#1]
when i am trying to run in any question of the option by your trivia bot script its showing result is 0.
![bot](https://user-images.githubusercontent.com/52373276/85099010-e5f22680-b219-11ea-9e54-75268d4922b2.PNG)

**Comment by Jayanthbm** [comment]
If You are on Wifi just restart the router and try it will work 
Google blocking your Ip so you are getting score as 0
